---
title: Tensors
authors:
  - name: Sébastien Boisgérault
    affiliations:
      - Mines Paris – PSL University
      - Institut des Transformations Numériques
---

In [1]:
import torch
import pandas as pd

## Getting Started

In [2]:
t = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])

In [3]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
keys = ["ndim", "shape", "dtype", "device"]
pd.DataFrame([{key: getattr(t, key) for key in keys}])

ndim   shape          dtype device
0     2  (2, 3)  torch.float32    cpu

In [5]:
t.data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
t0 = torch.tensor(1.0)
t0

tensor(1.)

In [7]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1

tensor([1., 2., 3.])

In [8]:
t2 = torch.tensor([[1.0, 2.0, 3.0], 
                   [4.0, 5.0, 6.0]])
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
t3 = torch.tensor([
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0], 
     [10.0, 11.0, 12.0]]
])
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [10]:
shapes = []
for t in [t0, t1, t2, t3]:
    shapes.append({"ndim": t.ndim, "shape": t.shape})
pd.DataFrame(shapes)

ndim      shape
0     0         ()
1     1       (3,)
2     2     (2, 3)
3     3  (2, 2, 3)

## Tensor Creation

In [11]:
torch.empty([2, 3])

tensor([[-2.9632e-03,  3.0841e-41, -2.9146e-06],
        [ 3.0841e-41,  0.0000e+00,  1.1755e-38]])

In [12]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand([2, 3])

tensor([[0.1797, 0.3440, 0.4487],
        [0.3222, 0.6317, 0.3918]])

In [15]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [16]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [17]:
torch.normal(0, 1, [2, 3])

tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

**TODO:** arange, linspace, logspace, zeros, ones, diag, randn, reshape, eye

## Indexing

In [18]:
t1

tensor([1., 2., 3.])

In [19]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
t2[1, 2]

tensor(6.)

In [21]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [22]:
t3[1, 1, 2]

tensor(12.)

In [23]:
t[-1, -1, -1]

tensor(12.)

In [24]:
t3[1, 1, :]

tensor([10., 11., 12.])

In [25]:
t3[0:2, 0:2, 0:3]

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [26]:
t3[0, 0, 0:3]

tensor([1., 2., 3.])

In [27]:
t3[0, 0:2, 0:3]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [28]:
t3[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
t3[0,...]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [30]:
t3 >= 4

tensor([[[False, False, False],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True]]])

In [31]:
t3[t3>=4]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## Tensor Calculus

### Vectorized Operations

In [32]:
t0

tensor(1.)

In [33]:
1.0 + t0

tensor(2.)

In [34]:
t0 + t0

tensor(2.)

In [35]:
2.0 * t0

tensor(2.)

In [36]:
t0 * t0

tensor(1.)

In [37]:
t0.sin()

tensor(0.8415)

In [38]:
torch.sin(t0)

tensor(0.8415)

In [39]:
t1

tensor([1., 2., 3.])

In [40]:
1.0 + t1

tensor([2., 3., 4.])

In [41]:
t1 + t1

tensor([2., 4., 6.])

In [42]:
2.0 * t1

tensor([2., 4., 6.])

In [43]:
t1 * t1

tensor([1., 4., 9.])

In [44]:
t1.sin()

tensor([0.8415, 0.9093, 0.1411])

In [45]:
torch.sin(t1)

tensor([0.8415, 0.9093, 0.1411])

In [46]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [47]:
1.0 + t2

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [48]:
2 * t2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [49]:
t2 * t2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [50]:
t2.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])

### Linear Algebra

See "02 - Linear Algebra.ipynb".

### Tensor contraction

In [51]:
t1 = torch.tensor([1.0, 2.0, 3.0])

In [52]:
torch.tensordot(t0, t0, dims=0)

tensor(1.)

In [53]:
torch.tensordot(t1, t1, dims=0)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

In [54]:
torch.tensordot(t1, t1, dims=1)

tensor(14.)

In [55]:
torch.tensordot(t2, t2, dims=0)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 2.,  4.,  6.],
          [ 8., 10., 12.]],

         [[ 3.,  6.,  9.],
          [12., 15., 18.]]],


        [[[ 4.,  8., 12.],
          [16., 20., 24.]],

         [[ 5., 10., 15.],
          [20., 25., 30.]],

         [[ 6., 12., 18.],
          [24., 30., 36.]]]])

In [56]:
torch.tensordot(t2, t2, dims=2) # dims=1 won't work

tensor(91.)

In [57]:
A = t2
print(A.shape)
A

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [58]:
B = torch.tensor([[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]])
print(B.shape)
torch.tensordot(A, B, dims=1)

torch.Size([3, 2])


tensor([[ 58.,  64.],
        [139., 154.]])

### Einstein Summation

In [59]:
x = t1

In [60]:
torch.einsum("i->i", x)

tensor([1., 2., 3.])

In [61]:
torch.einsum("i->", x)

tensor(6.)

In [62]:
A

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [63]:
torch.einsum("ij->ij", A)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [64]:
torch.einsum("ij->ji", A)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [65]:
torch.einsum("ij->i", A)

tensor([ 6., 15.])

In [66]:
torch.einsum("ij->j", A)

tensor([5., 7., 9.])

In [67]:
torch.einsum("ij->", A)

tensor(21.)

In [68]:
y = torch.tensor([4.0, 5.0, 6.0])

In [69]:
torch.einsum("i,j->ij", x, y)

tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])

In [70]:
torch.einsum("i,i->i", x, y)

tensor([ 4., 10., 18.])

In [71]:
torch.einsum("i,i->", x, y)

tensor(32.)

In [72]:
torch.einsum("ij,j->i", A, x)

tensor([14., 32.])

In [73]:
B

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [74]:
torch.einsum("ij,jk->ik", A, B)

tensor([[ 58.,  64.],
        [139., 154.]])

In [75]:
# batched matrices (1d batch dimension)
A = torch.rand((1000, 2, 3))
B = torch.rand((1000, 3, 4))
print(A)
print(B)

tensor([[[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062]],

        [[0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090]],

        ...,

        [[0.2120, 0.3880, 0.9504],
         [0.1482, 0.1198, 0.0930]],

        [[0.9678, 0.4361, 0.3670],
         [0.7741, 0.2046, 0.3679]],

        [[0.9583, 0.7663, 0.1121],
         [0.3626, 0.5491, 0.6807]]])
tensor([[[0.2700, 0.8501, 0.5078, 0.0677],
         [0.6340, 0.0146, 0.5348, 0.0055],
         [0.3574, 0.3838, 0.0509, 0.3586]],

        [[0.5168, 0.2183, 0.5710, 0.7640],
         [0.5590, 0.0092, 0.4984, 0.2657],
         [0.6425, 0.0988, 0.1541, 0.4834]],

        [[0.7883, 0.3664, 0.4736, 0.4505],
         [0.1088, 0.4604, 0.4859, 0.5828],
         [0.7238, 0.6489, 0.7788, 0.4047]],

        ...,

        [[0.1517, 0.0316, 0.1385, 0.0347],
         [0.0014, 0.9852, 0.7928, 0.7267],
         [0.8219, 0.6520, 0.3348, 0.4379]],

        [[0.2945

In [76]:
torch.einsum("bij,bjk->bik", A, B)

tensor([[[0.5661, 0.3393, 0.4847, 0.1182],
         [0.6046, 0.6987, 0.4252, 0.3297]],

        [[0.4356, 0.0609, 0.2498, 0.3255],
         [0.4129, 0.0492, 0.3875, 0.3007]],

        [[1.3996, 0.9583, 1.1773, 0.8311],
         [1.0820, 0.8941, 1.0704, 0.7869]],

        ...,

        [[0.8139, 1.0086, 0.6552, 0.7055],
         [0.0991, 0.1833, 0.1466, 0.1329]],

        [[0.7176, 0.8273, 1.2021, 0.5260],
         [0.5272, 0.6604, 0.8782, 0.3827]],

        [[0.7488, 0.3581, 0.4094, 0.9383],
         [0.3490, 0.4296, 0.5126, 0.8025]]])

In [77]:
# batched 2d
A = torch.rand((100, 100, 2, 2))
B = torch.rand((100, 100, 2, 2))

In [78]:
bp = torch.einsum("...ij,...jk->...ik", A, B)
bp

tensor([[[[0.3181, 0.2667],
          [0.2160, 0.2736]],

         [[0.9795, 0.4558],
          [1.0185, 0.7780]],

         [[0.4357, 0.0413],
          [0.9145, 0.0362]],

         ...,

         [[0.2016, 0.6067],
          [0.2655, 0.7060]],

         [[0.6581, 0.6382],
          [0.5127, 0.4880]],

         [[0.3391, 0.6057],
          [0.2761, 0.4059]]],


        [[[0.6925, 0.2154],
          [0.2242, 0.0712]],

         [[0.0919, 0.4576],
          [0.1934, 0.7343]],

         [[0.4514, 0.1329],
          [0.5043, 0.1474]],

         ...,

         [[0.1208, 0.8345],
          [0.4981, 0.6098]],

         [[0.2566, 0.6685],
          [0.4046, 0.2397]],

         [[0.4188, 0.9162],
          [0.3849, 0.8630]]],


        [[[0.3212, 0.2060],
          [0.7521, 0.4776]],

         [[0.4480, 0.6323],
          [0.0561, 0.1581]],

         [[0.2106, 0.1452],
          [0.6411, 0.4585]],

         ...,

         [[0.1711, 0.2433],
          [0.2486, 0.3530]],

         [[0.6821, 0.46

In [79]:
bp.shape

torch.Size([100, 100, 2, 2])

## Reshaping

### Flatten, squeeze and reshape

```{tip}
The following operations do not change the order of elements of in tensors, only their shape.
```

```{note}
`flatten` makes a tensor 1-dimensional
```

In [80]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [81]:
t3.shape

torch.Size([2, 2, 3])

In [82]:
t3.flatten()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [83]:
t3.flatten().shape

torch.Size([12])

You can also selectively flatten a tensor along *some* of its dimensions:

In [84]:
t3.flatten(0, 1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [85]:
t3.flatten(0, 1).shape

torch.Size([4, 3])

```{note}
`squeeze` remove the dimensions with only one element.
```

In [86]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [87]:
t.shape

torch.Size([1, 3, 2, 1])

In [88]:
t.squeeze()

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [89]:
t.squeeze().shape

torch.Size([3, 2])

You can also select only some (trivial) dimensions to be removed:

In [90]:
t.squeeze(0)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]])

In [91]:
t.squeeze(0).shape

torch.Size([3, 2, 1])

In [92]:
t.squeeze(3)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [93]:
t.squeeze(3).shape

torch.Size([1, 3, 2])

In [94]:
t.squeeze((0, 3))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [95]:
t.squeeze((0, 3)).shape

torch.Size([3, 2])

```{note}
`flatten` and `squeeze` are special cases of `reshape`.
```

In [96]:
t3.reshape(2*2*3)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [97]:
t3.reshape(2*2*3).shape

torch.Size([12])

In [98]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t.shape

torch.Size([1, 3, 2, 1])

In [99]:
t.reshape([3, 2])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [100]:
t.reshape([3, 2]).shape

torch.Size([3, 2])

In [101]:
t3.reshape([3, 4])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [102]:
t3.reshape([1, 2, 6])

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]])

In [103]:
t3.reshape([1, 2, 6]).shape

torch.Size([1, 2, 6])

Since the product of all shape coefficients is the number of elements and should be preserved, one of the coefficients can always be automatically deduced; use `-1` to let pytorch compute it.

In [104]:
t3.reshape([1, 2, -1]).shape

torch.Size([1, 2, 6])

In [105]:
t3.reshape([-1]).shape

torch.Size([12])

### Transposition and Permutation

In [106]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [107]:
t2.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [108]:
t2.transpose(0, 1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [109]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [110]:
t3.shape

torch.Size([2, 2, 3])

In [111]:
t3.transpose(0, 1)

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])

In [112]:
t3.transpose(0, 1).shape

torch.Size([2, 2, 3])

In [113]:
t3.transpose(0, 2)

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [114]:
t3.transpose(0, 2).shape

torch.Size([3, 2, 2])

In [115]:
t3.permute([2, 1, 0])

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [116]:
t3.permute([0, 2, 1])

tensor([[[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])

In [117]:
t3.permute([0, 2, 1]).shape

torch.Size([2, 3, 2])

### Concatenation and Stacking

In [118]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
torch.cat((A, B))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [119]:
C = torch.cat((A, B))
D = C[:,0:1]
E = C[:,1:]
torch.cat((D, E), dim=1)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [120]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([3.0, 4.0, 5.0])
s = torch.stack((x, y))
s

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [121]:
x.shape, s.shape

(torch.Size([3]), torch.Size([2, 3]))

In [122]:
s = torch.stack((x, y), dim=1)
s.shape

torch.Size([3, 2])

In [123]:
s = torch.stack((x, y), dim=1)
s.shape

torch.Size([3, 2])

In [124]:
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

In [125]:
torch.stack((A, B))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [126]:
torch.stack((A, B), dim=0)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [127]:
torch.stack((A, B), dim=1)

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])

In [128]:
torch.stack((A, B), dim=2)

tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])

### Expansion and Broadcasting

In [129]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [130]:
t.shape

torch.Size([1, 3, 2, 1])

Duplicate the elements along (some of)  the dimensions with a depth of 1:

In [131]:
t.expand([1, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [132]:
t.expand([1, 3, 2, 2]).shape

torch.Size([1, 3, 2, 2])

In [133]:
t.expand([3, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [134]:
t.expand([3, 3, 2, 2]).shape

torch.Size([3, 3, 2, 2])

You can also prepend new dimensions:

In [135]:
t1

tensor([1., 2., 3.])

In [136]:
t1.shape

torch.Size([3])

In [137]:
t1.expand([4, 1, 2, 3])

tensor([[[[1., 2., 3.],
          [1., 2., 3.]]],


        [[[1., 2., 3.],
          [1., 2., 3.]]],


        [[[1., 2., 3.],
          [1., 2., 3.]]],


        [[[1., 2., 3.],
          [1., 2., 3.]]]])

In [138]:
t1.expand([4, 1, 2, 3]).shape

torch.Size([4, 1, 2, 3])

Some binary operations automatically perform the appropriate expansions on their arguments if their shapes are somehow consistent or *broadcastable*; [the rules are](https://pytorch.org/docs/stable/notes/broadcasting.html#general-semantics):


```{note}
Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.
```


Example with the addition:

In [139]:
r = torch.rand([2, 1, 3])

In [140]:
r

tensor([[[0.0923, 0.5446, 0.1036]],

        [[0.8714, 0.0069, 0.5580]]])

In [141]:
s = torch.rand([3, 2, 2, 1])
s

tensor([[[[0.0295],
          [0.6339]],

         [[0.1238],
          [0.3136]]],


        [[[0.8994],
          [0.1326]],

         [[0.4694],
          [0.1832]]],


        [[[0.6595],
          [0.4426]],

         [[0.0872],
          [0.8993]]]])

In [142]:
r + s

tensor([[[[0.1219, 0.5741, 0.1331],
          [0.7263, 1.1785, 0.7375]],

         [[0.9953, 0.1307, 0.6818],
          [1.1850, 0.3205, 0.8716]]],


        [[[0.9917, 1.4440, 1.0029],
          [0.2249, 0.6772, 0.2362]],

         [[1.3408, 0.4763, 1.0274],
          [1.0547, 0.1901, 0.7412]]],


        [[[0.7518, 1.2041, 0.7631],
          [0.5350, 0.9872, 0.5462]],

         [[0.9586, 0.0941, 0.6452],
          [1.7708, 0.9062, 1.4573]]]])

In [143]:
(r + s).shape

torch.Size([3, 2, 2, 3])