---
title: Tensors
authors:
  - name: Sébastien Boisgérault
    affiliations:
      - Mines Paris – PSL University
      - Institut des Transformations Numériques
---

In [1]:
import torch
import pandas as pd

## Getting Started

In [2]:
t = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])

In [3]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
keys = ["ndim", "shape", "dtype", "device"]
pd.DataFrame([{key: getattr(t, key) for key in keys}])

ndim   shape          dtype device
0     2  (2, 3)  torch.float32    cpu

In [5]:
t.data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
t0 = torch.tensor(1.0)
t0

tensor(1.)

In [7]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1

tensor([1., 2., 3.])

In [8]:
t2 = torch.tensor([[1.0, 2.0, 3.0], 
                   [4.0, 5.0, 6.0]])
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
t3 = torch.tensor([
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0], 
     [10.0, 11.0, 12.0]]
])
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [10]:
shapes = []
for t in [t0, t1, t2, t3]:
    shapes.append({"ndim": t.ndim, "shape": t.shape})
pd.DataFrame(shapes)

ndim      shape
0     0         ()
1     1       (3,)
2     2     (2, 3)
3     3  (2, 2, 3)

## Tensor Creation

In [11]:
torch.empty([2, 3])

tensor([[1.8445e-26, 4.5588e-41, 1.9057e-04],
        [3.0822e-41, 4.4842e-44, 0.0000e+00]])

In [12]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand([2, 3])

tensor([[0.3652, 0.7918, 0.2003],
        [0.7467, 0.9858, 0.2068]])

In [15]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [16]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [17]:
torch.normal(0, 1, [2, 3])

tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

**TODO:** arange, linspace, logspace, zeros, ones, diag, randn, reshape, eye

## Indexing

In [104]:
t1

tensor([1., 2., 3.])

In [106]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [107]:
t2[1, 2]

tensor(6.)

In [18]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [95]:
t3[1, 1, 2]

tensor(12.)

In [96]:
t[-1, -1, -1]

tensor([6.])

In [98]:
t3[1, 1, :]

tensor([10., 11., 12.])

In [109]:
t3[0:2, 0:2, 0:3]

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [110]:
t3[0, 0, 0:3]

tensor([1., 2., 3.])

In [112]:
t3[0, 0:2, 0:3]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [113]:
t3[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [114]:
t3[0,...]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [115]:
t3 >= 4

tensor([[[False, False, False],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True]]])

In [116]:
t3[t3>=4]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## Tensor Calculus

### Vectorized Operations

In [19]:
t0

tensor(1.)

In [20]:
1.0 + t0

tensor(2.)

In [21]:
t0 + t0

tensor(2.)

In [22]:
2.0 * t0

tensor(2.)

In [23]:
t0 * t0

tensor(1.)

In [24]:
t0.sin()

tensor(0.8415)

In [25]:
torch.sin(t0)

tensor(0.8415)

In [26]:
t1

tensor([1., 2., 3.])

In [27]:
1.0 + t1

tensor([2., 3., 4.])

In [28]:
t1 + t1

tensor([2., 4., 6.])

In [29]:
2.0 * t1

tensor([2., 4., 6.])

In [30]:
t1 * t1

tensor([1., 4., 9.])

In [31]:
t1.sin()

tensor([0.8415, 0.9093, 0.1411])

In [32]:
torch.sin(t1)

tensor([0.8415, 0.9093, 0.1411])

In [117]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [118]:
1.0 + t2

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [119]:
2 * t2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [120]:
t2 * t2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [121]:
t2.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])

### Tensor contraction

In [33]:
t1 = torch.tensor([1.0, 2.0, 3.0])

In [34]:
torch.tensordot(t0, t0, dims=0)

tensor(1.)

In [35]:
torch.tensordot(t1, t1, dims=0)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

In [36]:
torch.tensordot(t1, t1, dims=1)

tensor(14.)

In [37]:
torch.tensordot(t2, t2, dims=0)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 2.,  4.,  6.],
          [ 8., 10., 12.]],

         [[ 3.,  6.,  9.],
          [12., 15., 18.]]],


        [[[ 4.,  8., 12.],
          [16., 20., 24.]],

         [[ 5., 10., 15.],
          [20., 25., 30.]],

         [[ 6., 12., 18.],
          [24., 30., 36.]]]])

In [38]:
torch.tensordot(t2, t2, dims=2) # dims=1 won't work

tensor(91.)

In [39]:
A = t2
print(A.shape)
A

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [40]:
B = torch.tensor([[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]])
print(B.shape)
torch.tensordot(A, B, dims=1)

torch.Size([3, 2])


tensor([[ 58.,  64.],
        [139., 154.]])

### Einstein Summation

In [122]:
x = t1

In [127]:
torch.einsum("i->i", x)

tensor([1., 2., 3.])

In [126]:
torch.einsum("i->", x)

tensor(6.)

In [128]:
A

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [129]:
torch.einsum("ij->ij", A)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [130]:
torch.einsum("ij->ji", A)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [131]:
torch.einsum("ij->i", A)

tensor([ 6., 15.])

In [132]:
torch.einsum("ij->j", A)

tensor([5., 7., 9.])

In [133]:
torch.einsum("ij->", A)

tensor(21.)

In [142]:
y = torch.tensor([4.0, 5.0, 6.0])

In [143]:
torch.einsum("i,j->ij", x, y)

tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])

In [144]:
torch.einsum("i,i->i", x, y)

tensor([ 4., 10., 18.])

In [145]:
torch.einsum("i,i->", x, y)

tensor(32.)

In [136]:
torch.einsum("ij,j->i", A, x)

tensor([14., 32.])

In [137]:
B

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [138]:
torch.einsum("ij,jk->ik", A, B)

tensor([[ 58.,  64.],
        [139., 154.]])

In [166]:
# batched matrices (1d batch dimension)
A = torch.rand((1000, 2, 3))
B = torch.rand((1000, 3, 4))
print(A)
print(B)

tensor([[[0.3775, 0.0309, 0.1349],
         [0.5361, 0.8623, 0.6925]],

        [[0.7557, 0.1269, 0.9070],
         [0.1849, 0.7705, 0.2959]],

        [[0.1424, 0.7983, 0.6559],
         [0.9992, 0.7818, 0.8166]],

        ...,

        [[0.2916, 0.9820, 0.5894],
         [0.3265, 0.1752, 0.4257]],

        [[0.6740, 0.2947, 0.0080],
         [0.0665, 0.4156, 0.6032]],

        [[0.5968, 0.5397, 0.8495],
         [0.3734, 0.7390, 0.2962]]])
tensor([[[0.3695, 0.8697, 0.5252, 0.6532],
         [0.5367, 0.1899, 0.6659, 0.5696],
         [0.0124, 0.4957, 0.9209, 0.7033]],

        [[0.6113, 0.3362, 0.6143, 0.2355],
         [0.7734, 0.3908, 0.5180, 0.6572],
         [0.6240, 0.5863, 0.6362, 0.5162]],

        [[0.3624, 0.3891, 0.6543, 0.1035],
         [0.0513, 0.9499, 0.3681, 0.0623],
         [0.0037, 0.9440, 0.9006, 0.3270]],

        ...,

        [[0.2420, 0.4480, 0.0139, 0.8700],
         [0.9796, 0.6819, 0.3875, 0.5906],
         [0.0137, 0.4753, 0.1296, 0.1220]],

        [[0.4856

In [167]:
torch.einsum("bij,bjk->bik", A, B)

tensor([[[0.1578, 0.4010, 0.3431, 0.3591],
         [0.6694, 0.9732, 1.4935, 1.3285]],

        [[1.1261, 0.8354, 1.1070, 0.7296],
         [0.8936, 0.5367, 0.7009, 0.7026]],

        [[0.0950, 1.4329, 0.9778, 0.2790],
         [0.4053, 1.9022, 1.6770, 0.4192]],

        ...,

        [[1.0406, 1.0803, 0.4609, 0.9055],
         [0.2564, 0.4680, 0.1276, 0.4394]],

        [[0.6115, 0.5591, 0.3435, 0.6446],
         [0.6336, 0.5835, 0.5049, 0.5640]],

        [[0.7677, 1.4165, 0.7184, 0.9702],
         [0.5724, 0.6944, 0.6572, 0.7402]]])

In [168]:
# batched 2d
A = torch.rand((100, 100, 2, 2))
B = torch.rand((100, 100, 2, 2))

In [170]:
bp = torch.einsum("...ij,...jk->...ik", A, B)
bp

tensor([[[[0.3459, 0.8305],
          [0.3560, 0.8204]],

         [[1.1230, 1.2292],
          [0.8418, 0.8086]],

         [[1.1237, 1.2790],
          [1.0012, 0.8363]],

         ...,

         [[0.3478, 0.2218],
          [0.8456, 0.6443]],

         [[0.3714, 0.8495],
          [0.0675, 0.2666]],

         [[0.3136, 0.6729],
          [0.3791, 0.7648]]],


        [[[0.5955, 0.4244],
          [0.8164, 0.5422]],

         [[0.5932, 0.4835],
          [0.6263, 0.7016]],

         [[1.2194, 0.7756],
          [1.0746, 0.6873]],

         ...,

         [[0.5020, 0.8419],
          [0.4349, 0.6900]],

         [[1.3474, 1.5139],
          [1.2460, 1.3429]],

         [[0.5622, 1.0386],
          [0.2519, 0.5268]]],


        [[[0.2400, 0.1419],
          [0.2136, 0.5271]],

         [[0.6443, 0.2518],
          [0.5591, 0.3209]],

         [[0.2461, 0.6204],
          [0.0569, 0.4761]],

         ...,

         [[0.8487, 0.8800],
          [0.7993, 0.7818]],

         [[0.7127, 0.26

In [171]:
bp.shape

torch.Size([100, 100, 2, 2])

## Reshaping

### Flatten, squeeze and reshape

```{tip}
The following operations do not change the order of elements of in tensors, only their shape.
```

```{note}
`flatten` makes a tensor 1-dimensional
```

In [41]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [42]:
t3.shape

torch.Size([2, 2, 3])

In [43]:
t3.flatten()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [44]:
t3.flatten().shape

torch.Size([12])

You can also selectively flatten a tensor along *some* of its dimensions:

In [45]:
t3.flatten(0, 1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [46]:
t3.flatten(0, 1).shape

torch.Size([4, 3])

```{note}
`squeeze` remove the dimensions with only one element.
```

In [47]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [48]:
t.shape

torch.Size([1, 3, 2, 1])

In [49]:
t.squeeze()

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [50]:
t.squeeze().shape

torch.Size([3, 2])

You can also select only some (trivial) dimensions to be removed:

In [51]:
t.squeeze(0)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]])

In [52]:
t.squeeze(0).shape

torch.Size([3, 2, 1])

In [53]:
t.squeeze(3)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [54]:
t.squeeze(3).shape

torch.Size([1, 3, 2])

In [55]:
t.squeeze((0, 3))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [56]:
t.squeeze((0, 3)).shape

torch.Size([3, 2])

```{note}
`flatten` and `squeeze` are special cases of `reshape`.
```

In [57]:
t3.reshape(2*2*3)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [58]:
t3.reshape(2*2*3).shape

torch.Size([12])

In [59]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t.shape

torch.Size([1, 3, 2, 1])

In [60]:
t.reshape([3, 2])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [61]:
t.reshape([3, 2]).shape

torch.Size([3, 2])

In [62]:
t3.reshape([3, 4])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [63]:
t3.reshape([1, 2, 6])

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]])

In [64]:
t3.reshape([1, 2, 6]).shape

torch.Size([1, 2, 6])

Since the product of all shape coefficients is the number of elements and should be preserved, one of the coefficients can always be automatically deduced; use `-1` to let pytorch compute it.

In [65]:
t3.reshape([1, 2, -1]).shape

torch.Size([1, 2, 6])

In [66]:
t3.reshape([-1]).shape

torch.Size([12])

### Transposition and Permutation

In [67]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [68]:
t2.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [69]:
t2.transpose(0, 1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [70]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [71]:
t3.shape

torch.Size([2, 2, 3])

In [72]:
t3.transpose(0, 1)

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])

In [73]:
t3.transpose(0, 1).shape

torch.Size([2, 2, 3])

In [74]:
t3.transpose(0, 2)

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [75]:
t3.transpose(0, 2).shape

torch.Size([3, 2, 2])

In [76]:
t3.permute([2, 1, 0])

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [77]:
t3.permute([0, 2, 1])

tensor([[[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])

In [78]:
t3.permute([0, 2, 1]).shape

torch.Size([2, 3, 2])

### Stacking

In [150]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([3.0, 4.0, 5.0])
s = torch.stack((x, y))
s

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [151]:
x.shape, s.shape

(torch.Size([3]), torch.Size([2, 3]))

In [152]:
s = torch.stack((x, y), dim=1)
s.shape

torch.Size([3, 2])

In [153]:
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

In [154]:
torch.stack((A, B))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [157]:
torch.stack((A, B), dim=2)

tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])

### Expansion and Broadcasting

In [79]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [80]:
t.shape

torch.Size([1, 3, 2, 1])

Duplicate the elements along (some of)  the dimensions with a depth of 1:

In [81]:
t.expand([1, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [82]:
t.expand([1, 3, 2, 2]).shape

torch.Size([1, 3, 2, 2])

In [83]:
t.expand([3, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [84]:
t.expand([3, 3, 2, 2]).shape

torch.Size([3, 3, 2, 2])

You can also prepend new dimensions:

In [85]:
t1

tensor([1., 2., 3.])

In [86]:
t1.shape

torch.Size([3])

In [87]:
t1.expand([4, 2, 3])

tensor([[[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]]])

In [88]:
t1.expand([4, 2, 3]).shape

torch.Size([4, 2, 3])

Some binary operations automatically perform the appropriate expansions on their arguments if their shapes are somehow consistent or *broadcastable*; [the rules are](https://pytorch.org/docs/stable/notes/broadcasting.html#general-semantics):


```{note}
Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.
```


Example with the addition:

In [89]:
r = torch.rand([2, 1, 3])

In [90]:
r

tensor([[[0.2666, 0.6274, 0.2696]],

        [[0.4414, 0.2969, 0.8317]]])

In [91]:
s = torch.rand([3, 2, 2, 1])
s

tensor([[[[0.1053],
          [0.2695]],

         [[0.3588],
          [0.1994]]],


        [[[0.5472],
          [0.0062]],

         [[0.9516],
          [0.0753]]],


        [[[0.8860],
          [0.5832]],

         [[0.3376],
          [0.8090]]]])

In [92]:
r + s

tensor([[[[0.3719, 0.7328, 0.3749],
          [0.5361, 0.8969, 0.5391]],

         [[0.8002, 0.6557, 1.1905],
          [0.6407, 0.4963, 1.0310]]],


        [[[0.8138, 1.1746, 0.8168],
          [0.2727, 0.6336, 0.2758]],

         [[1.3929, 1.2485, 1.7832],
          [0.5166, 0.3722, 0.9070]]],


        [[[1.1526, 1.5135, 1.1556],
          [0.8498, 1.2107, 0.8528]],

         [[0.7790, 0.6346, 1.1693],
          [1.2503, 1.1059, 1.6407]]]])

In [93]:
(r + s).shape

torch.Size([3, 2, 2, 3])