---
title: Tensors
authors:
  - name: Sébastien Boisgérault
    affiliations:
      - Mines Paris – PSL University
      - Institut des Transformations Numériques
---

In [1]:
import torch
import pandas as pd

## Getting Started

In [2]:
t = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])

In [3]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
keys = ["ndim", "shape", "dtype", "device"]
pd.DataFrame([{key: getattr(t, key) for key in keys}])

ndim   shape          dtype device
0     2  (2, 3)  torch.float32    cpu

In [5]:
t.data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
t0 = torch.tensor(1.0)
t0

tensor(1.)

In [7]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1

tensor([1., 2., 3.])

In [8]:
t2 = torch.tensor([[1.0, 2.0, 3.0], 
                   [4.0, 5.0, 6.0]])
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
t3 = torch.tensor([
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0], 
     [10.0, 11.0, 12.0]]
])
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [10]:
shapes = []
for t in [t0, t1, t2, t3]:
    shapes.append({"ndim": t.ndim, "shape": t.shape})
pd.DataFrame(shapes)

ndim      shape
0     0         ()
1     1       (3,)
2     2     (2, 3)
3     3  (2, 2, 3)

## Tensor Creation

In [11]:
torch.empty([2, 3])

tensor([[1.4341e-03, 3.0773e-41, 1.0893e-03],
        [3.0773e-41, 4.4842e-44, 0.0000e+00]])

In [12]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand([2, 3])

tensor([[0.4661, 0.3237, 0.4885],
        [0.6000, 0.4392, 0.3522]])

In [15]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [16]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [17]:
torch.normal(0, 1, [2, 3])

tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

**TODO:** arange, linspace, logspace, zeros, ones, diag, randn, reshape, eye

## Indexing (TODO)

## Tensor Calculus

TODO:
  - broadcasting
  - `*` vs `@` (`matmul`) vs `dot` vs `tensordot`

In [18]:
t0

tensor(1.)

In [19]:
1.0 + t0

tensor(2.)

In [20]:
t0 + t0

tensor(2.)

In [21]:
2.0 * t0

tensor(2.)

In [22]:
t0 * t0

tensor(1.)

In [23]:
t0.sin()

tensor(0.8415)

In [24]:
torch.sin(t0)

tensor(0.8415)

In [25]:
t1

tensor([1., 2., 3.])

In [26]:
1.0 + t1

tensor([2., 3., 4.])

In [27]:
t1 + t1

tensor([2., 4., 6.])

In [28]:
2.0 * t1

tensor([2., 4., 6.])

In [29]:
t1 * t1

tensor([1., 4., 9.])

In [30]:
t1.sin()

tensor([0.8415, 0.9093, 0.1411])

In [31]:
torch.sin(t1)

tensor([0.8415, 0.9093, 0.1411])

In [32]:
t1 = torch.tensor([1.0, 2.0, 3.0])

In [33]:
torch.tensordot(t0, t0, dims=0)

tensor(1.)

In [34]:
torch.tensordot(t1, t1, dims=0)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

In [35]:
torch.tensordot(t1, t1, dims=1)

tensor(14.)

In [36]:
torch.tensordot(t2, t2, dims=0)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 2.,  4.,  6.],
          [ 8., 10., 12.]],

         [[ 3.,  6.,  9.],
          [12., 15., 18.]]],


        [[[ 4.,  8., 12.],
          [16., 20., 24.]],

         [[ 5., 10., 15.],
          [20., 25., 30.]],

         [[ 6., 12., 18.],
          [24., 30., 36.]]]])

In [37]:
torch.tensordot(t2, t2, dims=2) # dims=1 won't work

tensor(91.)

In [38]:
A = t2
print(A.shape)
A

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [39]:
B = torch.tensor([[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]])
print(B.shape)
torch.tensordot(A, B, dims=1)

torch.Size([3, 2])


tensor([[ 58.,  64.],
        [139., 154.]])

**TODO** internal contraction with tensordot with eye

**TODO** special cases: matrix vector product, matrix matrix product, scalar product between two vectors, vector matrix product (yay!)

**TODO** general contraction formula / process

**TODO** dims as a list of pairs, einsum (generalisation of tensordot)

## Reshaping

TODO