---
title: Tensors
authors:
  - name: Sébastien Boisgérault
    affiliations:
      - Mines Paris – PSL University
      - Institut des Transformations Numériques
---

In [1]:
import torch
import pandas as pd

## Getting Started

In [2]:
t = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])

In [3]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
keys = ["ndim", "shape", "dtype", "device"]
pd.DataFrame([{key: getattr(t, key) for key in keys}])

ndim   shape          dtype device
0     2  (2, 3)  torch.float32    cpu

In [5]:
t.data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
t0 = torch.tensor(1.0)
t0

tensor(1.)

In [7]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1

tensor([1., 2., 3.])

In [8]:
t2 = torch.tensor([[1.0, 2.0, 3.0], 
                   [4.0, 5.0, 6.0]])
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
t3 = torch.tensor([
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0], 
     [10.0, 11.0, 12.0]]
])
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [10]:
shapes = []
for t in [t0, t1, t2, t3]:
    shapes.append({"ndim": t.ndim, "shape": t.shape})
pd.DataFrame(shapes)

ndim      shape
0     0         ()
1     1       (3,)
2     2     (2, 3)
3     3  (2, 2, 3)

## Tensor Creation

In [11]:
torch.empty([2, 3])

tensor([[6.4492e-26, 3.0750e-41, 3.3063e-26],
        [3.0750e-41, 1.1210e-43, 0.0000e+00]])

In [12]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand([2, 3])

tensor([[0.3448, 0.5441, 0.8133],
        [0.3914, 0.1563, 0.3254]])

In [15]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [16]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [17]:
torch.normal(0, 1, [2, 3])

tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

**TODO:** arange, linspace, logspace, zeros, ones, diag, randn, reshape, eye

## Indexing (TODO)

## Tensor Calculus

TODO:
  - `*` vs `@` (`matmul`) vs `dot` vs `tensordot`

In [18]:
t0

tensor(1.)

In [19]:
1.0 + t0

tensor(2.)

In [20]:
t0 + t0

tensor(2.)

In [21]:
2.0 * t0

tensor(2.)

In [22]:
t0 * t0

tensor(1.)

In [23]:
t0.sin()

tensor(0.8415)

In [24]:
torch.sin(t0)

tensor(0.8415)

In [25]:
t1

tensor([1., 2., 3.])

In [26]:
1.0 + t1

tensor([2., 3., 4.])

In [27]:
t1 + t1

tensor([2., 4., 6.])

In [28]:
2.0 * t1

tensor([2., 4., 6.])

In [29]:
t1 * t1

tensor([1., 4., 9.])

In [30]:
t1.sin()

tensor([0.8415, 0.9093, 0.1411])

In [31]:
torch.sin(t1)

tensor([0.8415, 0.9093, 0.1411])

In [32]:
t1 = torch.tensor([1.0, 2.0, 3.0])

In [33]:
torch.tensordot(t0, t0, dims=0)

tensor(1.)

In [34]:
torch.tensordot(t1, t1, dims=0)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

In [35]:
torch.tensordot(t1, t1, dims=1)

tensor(14.)

In [36]:
torch.tensordot(t2, t2, dims=0)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 2.,  4.,  6.],
          [ 8., 10., 12.]],

         [[ 3.,  6.,  9.],
          [12., 15., 18.]]],


        [[[ 4.,  8., 12.],
          [16., 20., 24.]],

         [[ 5., 10., 15.],
          [20., 25., 30.]],

         [[ 6., 12., 18.],
          [24., 30., 36.]]]])

In [37]:
torch.tensordot(t2, t2, dims=2) # dims=1 won't work

tensor(91.)

In [38]:
A = t2
print(A.shape)
A

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [39]:
B = torch.tensor([[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]])
print(B.shape)
torch.tensordot(A, B, dims=1)

torch.Size([3, 2])


tensor([[ 58.,  64.],
        [139., 154.]])

**TODO** internal contraction with tensordot with eye

**TODO** special cases: matrix vector product, matrix matrix product, scalar product between two vectors, vector matrix product (yay!)

**TODO** general contraction formula / process

**TODO** dims as a list of pairs, einsum (generalisation of tensordot)

## Reshaping

### Flatten, squeeze and reshape

```{tip}
The following operations do not change the order of elements of in tensors, only their shape.
```

```{note}
`flatten` makes a tensor 1-dimensional
```

In [40]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [41]:
t3.shape

torch.Size([2, 2, 3])

In [42]:
t3.flatten()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [43]:
t3.flatten().shape

torch.Size([12])

You can also selectively flatten a tensor along *some* of its dimensions:

In [44]:
t3.flatten(0, 1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [45]:
t3.flatten(0, 1).shape

torch.Size([4, 3])

```{note}
`squeeze` remove the dimensions with only one element.
```

In [46]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [47]:
t.shape

torch.Size([1, 3, 2, 1])

In [48]:
t.squeeze()

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [49]:
t.squeeze().shape

torch.Size([3, 2])

You can also select only some (trivial) dimensions to be removed:

In [50]:
t.squeeze(0)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]])

In [51]:
t.squeeze(0).shape

torch.Size([3, 2, 1])

In [52]:
t.squeeze(3)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [53]:
t.squeeze(3).shape

torch.Size([1, 3, 2])

In [54]:
t.squeeze((0, 3))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [55]:
t.squeeze((0, 3)).shape

torch.Size([3, 2])

```{note}
`flatten` and `squeeze` are special cases of `reshape`.
```

In [70]:
t3.reshape(2*2*3)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [71]:
t3.reshape(2*2*3).shape

torch.Size([12])

In [74]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t.shape

torch.Size([1, 3, 2, 1])

In [75]:
t.reshape([3, 2])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [76]:
t.reshape([3, 2]).shape

torch.Size([3, 2])

In [72]:
t3.reshape([3, 4])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [77]:
t3.reshape([1, 2, 6])

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]])

In [78]:
t3.reshape([1, 2, 6]).shape

torch.Size([1, 2, 6])

Since the product of all shape coefficients is the number of elements and should be preserved, one of the coefficients can always be automatically deduced; use `-1` to let pytorch compute it.

In [79]:
t3.reshape([1, 2, -1]).shape

torch.Size([1, 2, 6])

In [81]:
t3.reshape([-1]).shape

torch.Size([12])

### Transposition and Permutation

In [56]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [57]:
t2.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [58]:
t2.transpose(0, 1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [59]:
t3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [60]:
t3.shape

torch.Size([2, 2, 3])

In [61]:
t3.transpose(0, 1)

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])

In [62]:
t3.transpose(0, 1).shape

torch.Size([2, 2, 3])

In [63]:
t3.transpose(0, 2)

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [64]:
t3.transpose(0, 2).shape

torch.Size([3, 2, 2])

In [65]:
t3.permute([2, 1, 0])

tensor([[[ 1.,  7.],
         [ 4., 10.]],

        [[ 2.,  8.],
         [ 5., 11.]],

        [[ 3.,  9.],
         [ 6., 12.]]])

In [66]:
t3.permute([0, 2, 1])

tensor([[[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])

In [67]:
t3.permute([0, 2, 1]).shape

torch.Size([2, 3, 2])

### Expansion and Broadcasting

In [86]:
t = torch.tensor([[[[1.0], [2.0]], [[3.0], [4.0]], [[5.0], [6.0]]]])
t

tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]],

         [[5.],
          [6.]]]])

In [87]:
t.shape

torch.Size([1, 3, 2, 1])

Duplicate the elements along (some of)  the dimensions with a depth of 1:

In [88]:
t.expand([1, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [89]:
t.expand([1, 3, 2, 2]).shape

torch.Size([1, 3, 2, 2])

In [90]:
t.expand([3, 3, 2, 2])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]],


        [[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]],

         [[5., 5.],
          [6., 6.]]]])

In [91]:
t.expand([3, 3, 2, 2]).shape

torch.Size([3, 3, 2, 2])

You can also prepend new dimensions:

In [92]:
t1

tensor([1., 2., 3.])

In [93]:
t1.shape

torch.Size([3])

In [95]:
t1.expand([4, 2, 3])

tensor([[[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]]])

In [96]:
t1.expand([4, 2, 3]).shape

torch.Size([4, 2, 3])

Some binary operations automatically perform the appropriate expansions on their arguments if their shapes are somehow consistent or *broadcastable*; [the rules are](https://pytorch.org/docs/stable/notes/broadcasting.html#general-semantics):


```{note}
Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.
```


Example with the addition:

In [99]:
r = torch.rand([2, 1, 3])

In [100]:
r

tensor([[[0.6057, 0.3725, 0.7980]],

        [[0.8399, 0.1374, 0.2331]]])

In [101]:
s = torch.rand([3, 2, 2, 1])
s

tensor([[[[0.9578],
          [0.3313]],

         [[0.3227],
          [0.0162]]],


        [[[0.2137],
          [0.6249]],

         [[0.4340],
          [0.1371]]],


        [[[0.5117],
          [0.1585]],

         [[0.0758],
          [0.2247]]]])

In [102]:
r + s

tensor([[[[1.5635, 1.3304, 1.7559],
          [0.9370, 0.7038, 1.1293]],

         [[1.1626, 0.4602, 0.5558],
          [0.8561, 0.1536, 0.2493]]],


        [[[0.8194, 0.5862, 1.0117],
          [1.2306, 0.9974, 1.4229]],

         [[1.2739, 0.5714, 0.6671],
          [0.9770, 0.2745, 0.3701]]],


        [[[1.1174, 0.8842, 1.3098],
          [0.7642, 0.5310, 0.9565]],

         [[0.9157, 0.2132, 0.3089],
          [1.0646, 0.3621, 0.4577]]]])

In [103]:
(r + s).shape

torch.Size([3, 2, 2, 3])