# Linear Algebra

In [1]:
import torch
from torch import tensor

## Vectors

In [2]:
u = tensor([[1.0], 
            [2.0]])
u

tensor([[1.],
        [2.]])

In [3]:
alpha = 2.0
alpha * u

tensor([[2.],
        [4.]])

In [4]:
v = tensor([[3.0], 
            [4.0]])
v

tensor([[3.],
        [4.]])

In [5]:
u + v

tensor([[4.],
        [6.]])

## Matrix-Vector Product

In [6]:
A = tensor([[1.0, 2.0],
            [3.0, 4.0]])
A

tensor([[1., 2.],
        [3., 4.]])

In [7]:
x = tensor([[1.0], [2.0]])
x

tensor([[1.],
        [2.]])

In [8]:
A * x # Not what you expect AT ALL! 

tensor([[1., 2.],
        [6., 8.]])

In [9]:
y = A @ x
y

tensor([[ 5.],
        [11.]])

## Matrix Product

In [10]:
B = tensor([[0.0, 1.0],
            [1.0, 0.0]])
B

tensor([[0., 1.],
        [1., 0.]])

In [11]:
A * B

tensor([[0., 2.],
        [3., 0.]])

In [12]:
A @ B

tensor([[2., 1.],
        [4., 3.]])

In [13]:
C = torch.rand((2, 3))
C

tensor([[0.0981, 0.7248, 0.4123],
        [0.5671, 0.0765, 0.2497]])

In [14]:
D = torch.rand((3, 4))

In [15]:
E = C @ D
E

tensor([[0.4661, 0.4342, 0.5188, 0.5583],
        [0.2239, 0.1456, 0.3247, 0.2532]])

In [16]:
E.shape

torch.Size([2, 4])

# Transposition

In [17]:
x

tensor([[1.],
        [2.]])

In [18]:
x.T

tensor([[1., 2.]])

In [19]:
A

tensor([[1., 2.],
        [3., 4.]])

In [20]:
A.T

tensor([[1., 3.],
        [2., 4.]])

In [21]:
C

tensor([[0.0981, 0.7248, 0.4123],
        [0.5671, 0.0765, 0.2497]])

In [22]:
C.T

tensor([[0.0981, 0.5671],
        [0.7248, 0.0765],
        [0.4123, 0.2497]])

In [23]:
x.T @ A

tensor([[ 7., 10.]])

In [24]:
x.T @ y

tensor([[27.]])

In [25]:
(x.T @ y)[0, 0]

tensor(27.)

In [26]:
(x.T @ y).squeeze()

tensor(27.)

In [27]:
(x.T @ y).item()

27.0

In [28]:
x.T @ A @ x

tensor([[27.]])

In [29]:
x @ x.T

tensor([[1., 2.],
        [2., 4.]])

## Tensorisation

Forget about row vectors vs column vectors (which are matrices), describe them as 1-d tensors.

In [30]:
x

tensor([[1.],
        [2.]])

In [31]:
x.shape

torch.Size([2, 1])

In [32]:
x.squeeze()

tensor([1., 2.])

In [33]:
x = tensor([1., 2.])

In [34]:
y = A @ x
y

tensor([ 5., 11.])

In [35]:
A @ B

tensor([[2., 1.],
        [4., 3.]])

In [36]:
# x.T # doesn't make sense, warning at least

In [49]:
x @ A @ x

tensor(27.)

In [38]:
# What about x.T @ x ? Nah, does not work now

The operator `@` has a bunch of special cases in its [definition](https://pytorch.org/docs/stable/generated/torch.matmul.html). The situation is simpler when you consider `torch.tensordot` (the tensor contraction) instead.

In [39]:
td = torch.tensordot 

In [50]:
y = td(A, x, 1)

In [51]:
td(A, B, 1)

tensor([[2., 1.],
        [4., 3.]])

In [52]:
td(y, x, 1)

tensor(27.)

## Linear Algebra Operations

In [54]:
import torch.linalg as la

In [55]:
A

tensor([[1., 2.],
        [3., 4.]])

In [56]:
x

tensor([1., 2.])

In [57]:
la.norm(x)

tensor(2.2361)

In [59]:
la.norm(A)

tensor(5.4772)

In [67]:
la.norm(A.flatten())

tensor(5.4772)

See also: [`vector_norm`]  and [`matrix_norm`]

[`vector_norm`]: https://pytorch.org/docs/stable/generated/torch.linalg.vector_norm.html#torch.linalg.vector_norm
[`matrix_norm`]: https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html#torch.linalg.matrix_norm

In [60]:
la.inv(A)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [61]:
la.inv(A) @ x

tensor([0.0000, 0.5000])

In [62]:
la.solve(A, x)

tensor([0.0000, 0.5000])

In [64]:
vals, vectors = la.eig(A)

In [65]:
vals

tensor([-0.3723+0.j,  5.3723+0.j])

In [66]:
vectors

tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])