In [59]:
import torch

## Tensors

In [60]:
t0 = torch.tensor(1.0)
t0

tensor(1.)

In [61]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1

tensor([1., 2., 3.])

In [62]:
t2 = torch.tensor([[1.0, 2.0, 3.0], 
                   [4.0, 5.0, 6.0]])
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [63]:
print(f"{t0.ndim = }")
print(f"{t0.shape = }")
print(f"{t0.dtype = }")

t0.ndim = 0
t0.shape = torch.Size([])
t0.dtype = torch.float32


In [64]:
print(f"{t1.ndim = }")
print(f"{t1.shape = }")
print(f"{t0.dtype = }")

t1.ndim = 1
t1.shape = torch.Size([3])
t0.dtype = torch.float32


In [65]:
print(f"{t2.ndim = }")
print(f"{t2.shape = }")
print(f"{t0.dtype = }")

t2.ndim = 2
t2.shape = torch.Size([2, 3])
t0.dtype = torch.float32


## Tensor Creation

In [66]:
torch.empty([2, 3])

tensor([[-2.3909e-26,  3.0694e-41, -2.4709e-26],
        [ 3.0694e-41,  0.0000e+00,  0.0000e+00]])

In [67]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [68]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [69]:
torch.rand([2, 3])

tensor([[0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])

In [70]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [71]:
torch.manual_seed(42)
torch.rand([2, 3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [72]:
torch.normal(0, 1, [2, 3])

tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

**TODO:** arange, linspace, logspace, zeros, ones, diag, randn, reshape, eye

## Indexing (TODO)

## Tensor Calculus

TODO:
  - broadcasting
  - `*` vs `@` (`matmul`) vs `dot` vs `tensordot`

In [73]:
t0

tensor(1.)

In [74]:
1.0 + t0

tensor(2.)

In [75]:
t0 + t0

tensor(2.)

In [76]:
2.0 * t0

tensor(2.)

In [77]:
t0 * t0

tensor(1.)

In [78]:
t0.sin()

tensor(0.8415)

In [79]:
torch.sin(t0)

tensor(0.8415)

In [80]:
t1

tensor([1., 2., 3.])

In [85]:
1.0 + t1

tensor([2., 3., 4.])

In [82]:
t1 + t1

tensor([2., 4., 6.])

In [86]:
2.0 * t1

tensor([2., 4., 6.])

In [83]:
t1 * t1

tensor([1., 4., 9.])

In [87]:
t1.sin()

tensor([0.8415, 0.9093, 0.1411])

In [88]:
torch.sin(t1)

tensor([0.8415, 0.9093, 0.1411])

In [92]:
t1 = torch.tensor([1.0, 2.0, 3.0])

In [95]:
torch.tensordot(t0, t0, dims=0)

tensor(1.)

In [96]:
torch.tensordot(t1, t1, dims=0)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

In [97]:
torch.tensordot(t1, t1, dims=1)

tensor(14.)

In [98]:
torch.tensordot(t2, t2, dims=0)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 2.,  4.,  6.],
          [ 8., 10., 12.]],

         [[ 3.,  6.,  9.],
          [12., 15., 18.]]],


        [[[ 4.,  8., 12.],
          [16., 20., 24.]],

         [[ 5., 10., 15.],
          [20., 25., 30.]],

         [[ 6., 12., 18.],
          [24., 30., 36.]]]])

In [101]:
torch.tensordot(t2, t2, dims=2) # dims=1 won't work

tensor(91.)

In [103]:
A = t2
print(A.shape)
A

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [106]:
B = torch.tensor([[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]])
print(B.shape)
torch.tensordot(A, B, dims=1)

torch.Size([3, 2])


tensor([[ 58.,  64.],
        [139., 154.]])

**TODO** internal contraction with tensordot with eye

**TODO** special cases: matrix vector product, matrix matrix product, scalar product between two vectors, vector matrix product (yay!)

**TODO** general contraction formula / process

**TODO** dims as a list of pairs, einsum (generalisation of tensordot)